version: "0.1.0"
services:
  db:
    build:
      dockerfile: DockerfilePostgres
      context: ./
    ports:
      - ${DB_PORT}:${DB_PORT}
    user: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - my-network
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - DB_SERVICE_NAME=db
      - DB_PORT=${DB_PORT}
      - API_PORT=${API_PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-network
    ports:
      - ${API_PORT}:${API_PORT}

networks:
  my-network :